# Generated by Django 3.1.1 on 2021-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_no',
            field=models.BigIntegerField(default=False),
        ),
    ]
