# Generated by Django 3.1.1 on 2021-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20210617_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default=False, max_length=50)),
                ('address', models.TextField(default=False, max_length=100)),
                ('number', models.IntegerField(default=False)),
            ],
        ),
    ]
