# Generated by Django 3.1.1 on 2021-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20210617_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontact',
            name='number',
            field=models.CharField(default=False, max_length=12),
        ),
    ]
